target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'shared', :path => '../shared'
  pod 'SDWebImageSwiftUI'
  pod 'mokoMvvmFlowSwiftUI', :podspec => 'https://raw.githubusercontent.com/icerockdev/moko-mvvm/release/0.16.1/mokoMvvmFlowSwiftUI.podspec'
end
